### PR TITLE
fix #603

### LINKED ISSUE #603: incompatible with IDEA 2019.3 EAP
`.ignore not loaded: until build 193.0 < IU-193.2956.37`

### PR DESCRIPTION
**Pull request by BorzdeG**

### CODE REVIEW

**Comment by BorzdeG** [comment]
@hsz , look PR?

**Comment by hsz** [comment]
Can you please refer to my two remaining questions?
It looks fine, but I'd like to understand the changes.

**Comment by BorzdeG** [comment]
questions? but here and in issue #603 I did not see questions from you :(

actually what i did:
1) deleted a method that is not used in IDEA and is not required in the plugin and its presence does not allow assembly in the latest versions of IDEA. Alternatively, you can leave the method, but remove the override from it, but is it necessary to leave the method that is not needed in the plugin itself?
2) removed the unnecessary explicit dependency of the class

**Comment by hsz** [comment]
That's interesting.
I've posted a screenshot with my view:

Screenshot_20191005-220052

**Comment by BorzdeG** [comment]
It seems you did not send them. I will answer the screenshot ...

1) `build.gradle`: Gradle releases suggest updating the version and by default it is updated as `-bin`, not` -all`. Here I registered an explicit instruction for wrapper to write `all`. The version of Gradle wrapper itself can be removed - this is optional, which allows you to simply call `./gradlew wrapper` without passing the version - it is registered in the configuration.

2) `IgnoreManager.java`: as I wrote above, I removed the dependency from the constructor of the class. At the start-up phase, it is not needed and I received an error several times when the FileStatusManager has not yet been created (is null), and the plug-in is already trying to call it to assign it to the field. In the version that I did, we call FileStatusManager only when it is needed. The same VcsFileStatusProvider does exactly the same - he set an example for me.

**Comment by BorzdeG** [comment]
image

**Comment by BorzdeG** [comment]
I deleted the configuration for Gradle Wrapper - this is not a critical record and when updating Wrapper, you can also specify it in the command line through the parameters.

**Comment by hsz** [comment]
All right, and `statusManager` case - does it improve performance in any way? Or what's the purpose of this change?

**Comment by BorzdeG** [comment]
I did not see a drawdown in performance. But then I noticed that the error did not appear https://github.com/JetBrains/idea-gitignore/issues/603#issuecomment-533128234

**Comment by hsz** [comment]
Thank you for your effort Victor!

**Pull request merged**
